travis:
  secure:
    BINSTAR_TOKEN: dZTEkeROiG7JYVZ5a01JCuQDTnK62s4rWYnpm3INkQMQ3Om0W5GH4Zwi34qVEY4OVkZER/v3GsRmqm0JGrzVE+PubmbN6X19qC5qZ6u6r7iTTghYiOSxypbHrqEHDo2MJabuqA2ou547MS3wVRoE/fiFvw8bLeVjP/+dssYRnKAdrZOP1bhJBj3iY/zygZQMBJHS6eGeZYKtJQYjFDdnETL0YAlpf027hz+kngdaaWx/GnPOrgg960nj8S+BqDrkSQkDuqyayLhKTMp0saHx8op9AdZ5elZfgjot9dNWYxhtKnsUSnpNb1p+jPB1b0IT/4Bz9Ukj+0KGxhpEuBTwIwhyoC6lJBScFR/F1a61vme93l3EPduVWeCfUPaXFQQvByCfrWgM7AFpVZ416w9Ui5w5ZmCbCBwgWl3zbzGM7dLAeruYVT4/IN5vwKPxP2WngMD+bQRGFZrFIgzl0Hsbp6eSWFDDqOhC0P1eXmAAmQxJsZ8T+TSGBL5oBLD+4KzPA0R6NT+6PHtXQCyN2DnsHYmLyULC0hg55KuLf65HJSZGN5BAS0rgrfk7dwrmm8yD7UxrEZkK7Q1ZfEldLzsQpYpqlavf8wk0PEw/JzcN20R369PFVQAe2Kt3A81BACZlyU3ZjgRYxZGBwhUnQ0SRPadycdsqABlliIqrXf3H6tU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
